apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:u4CZztvhFu9uFmq++JFILdsbYBQPUC0Jx+F+agCsnC9AbvmNEitakQ==,iv:YtmPd6w7vAvDz4nq9fb/Jx5SRriDmKhTYtDQNFme1Fk=,tag:d2pnLDPyrt6bg3UV8pUgPg==,type:str]
sops:
  age:
    - recipient: age1qeu5ft3kqvvwz2pkdmmxw7vsrr6gydegmm7km25rqvqexkhga9gq228h6z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeG5seFRhZWwrNVhjMjNF
        S1pWSnBkTDVHVUxsaTMyZ3hxbGhIZnlaU1NFCkJKU3VGNDUxN09UNEFuRlJYTW90
        WkRTR1NKd25lUHhtakhzMWxaZ01MTE0KLS0tIDI2c25OSUU3OXNWdlFPMjZOQU5y
        enZJMFlQeEg4eElLOXAzVnZoZS9RZ3MK5Z4VX0Wszc3dnXEpItGWrgudRb3lOCSs
        PaoHHt/mp0Vi/vPqXdmmi57m1IQpAv8djedFyZS4dKBeXEEVDo3MXQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T17:55:46Z"
  mac: ENC[AES256_GCM,data:vkis/AzKvOwHmEmIf5JuoDlTsQkCFmqmsKoE5YkGJ0kzWGcQySKLOlxCNqcn4hYgn6JiUIdI7MDmnWrnyqpRBvDpowIHeWQY+O8xnxRjvqoUw4opOdrSAed8xSwE3oRKa8WJrZV6PDvgAdyYRKRDcPn397I1jsKd9VdiPAtjVzY=,iv:WYqC1LFLqvtIWZ5rjYzN1OwHf/X/52IYRquxXpxvnhs=,tag:BnWiE8Mpvc7WF+y0gdWmUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
