apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:t5uWH08ODdwviQ==,iv:jtPXXtL4DF43t7OQLyzog/YbW1n+NvViuHUzrpKIXUU=,tag:/6zOMEpAqKta5xGz1xfeQw==,type:str]
sops:
  age:
    - recipient: age1qeu5ft3kqvvwz2pkdmmxw7vsrr6gydegmm7km25rqvqexkhga9gq228h6z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMjNjd0FGVlpna09ZWUgv
        K3g5LzAyeS9ITnBFdDJLdzBXelA1M2tzcmxZCk9BSzNuZWFqZ3Q3cVc2czVBT01i
        QXBGUFVzTGtoMXdxbTFOMlRhbi9LQXMKLS0tIHRQTHFEZW45WjZzdE9sajZjcGtU
        SURodHowZUZjSlhTNmNSeFFvbHpPRzgKBwQebzJ9IqjWiCELy+KSnEWBg4veG7Yp
        /XyvNPrqyazyQNSnv2pFbNsT8TBZbQpHxYux7wm6b5BX6OUGefNG7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T17:55:46Z"
  mac: ENC[AES256_GCM,data:15kc7EjgNj5GOrXXAxKbmia6WRt4kY/Mtjpg/29GJgSkVGhVhQs2SNgJ8vu7CPPa3hjm0iAEitbo+OcjIfRgxVLKdNHVldW/xl8wyq2ZfNiD37WbUfc/92bWoXmyuEXbEQhBWx2Zq9eo7OQAWNQbHfYzAvaAyZiWpnj+yxKWQDY=,iv:2RZ8FlqI3Y4jMS9LcdyE3VcLeugAse6wrJmtF1YwRK0=,tag:WOrwzpAoCxfcVzJQZhN7IQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
