apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:79Z4T6VuPtYfveLG/NWmunTE0bu/n1aDT3KojyRKnZo=,iv:sEa34UgPvsSPLQ8GUztcNQu6Ia2iDxYEe3Mmue/Bw8U=,tag:keZPJmjmkZjFs9BBAaM0VA==,type:str]
sops:
  age:
    - recipient: age1qeu5ft3kqvvwz2pkdmmxw7vsrr6gydegmm7km25rqvqexkhga9gq228h6z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNzVMMjVIVFR6UEdxMEZp
        M3V3dUZDOGgxdUx0bUFpUDE4YWxRNndwMm13ClVGMG9VaWlJY3pNQTlBWVlFK0Vk
        dGR5eE5abE9taFo5aGVGSUZLcHEyam8KLS0tIDIrY0VnQlcvekx2ZFFNQkpTYTRO
        eC9VZjNsL2llMEZFTTVJaXV2MGEwNFEKnUOmg0x33N5DNihlQTGENclC+Sg3DWWn
        I1gvJBCM42HT5+BIqTqsagQKdEoLPEPQRXXVeXCcs0adxvvv73ahNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T17:55:46Z"
  mac: ENC[AES256_GCM,data:aDZLXLMf47F5fbaobnucJa3s0X9MwJ88abg3IWUfkO5iDSStVgrEU844MEcqDd1JnKvGSt9XAMyEtURRRWjoTVM3E4cEmOWE33psT7WKwW5p6cIl25m0MKAYVCpiuuxhmUtAn04XZEYodQH28IO9g/QPGOBAxW6X2aMT7LU6S0M=,iv:ubk/1PwDUBkOBWHK3aU84NyKSbadpdHzAniWcdwtXdk=,tag:qX1u1zdisJ/IbmpVXDlctA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
