apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:28gC0EBQ2b7Y6TLSTOg7G+qKoIiau+ggMMbSU5uCa2Y=,iv:9BjBiz+km+9f8yhniKHjRm2NQdZ8AFpgTTHQX4H+RWI=,tag:sd6ICBcWB70fZcm2AvXBNA==,type:str]
sops:
  age:
    - recipient: age1qeu5ft3kqvvwz2pkdmmxw7vsrr6gydegmm7km25rqvqexkhga9gq228h6z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQWNVU2tuRmk0czNyaFZB
        K1Qvb2JFbFIzenNaNmtsRGF6czZqSnFFazJVCmNTY2NMUDkrK3d0KzFQOVFWWENz
        eUxMTFo2S25vUndrRHZ1Nit0VER1ZkkKLS0tIGR6L3hPNHJTUExFdmtIMkNRNG9K
        Nm90K2ZPOE9TMXg4TjBpcllPWnhubjQKPXh7EmjDpASnf8zZS6oF6l16RUhR36d2
        MzaF6hXv+TMYAPCk4CNP6KNp4l/tFsfl7FSlSxc+zUe98yqLAsv87Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T17:02:23Z"
  mac: ENC[AES256_GCM,data:09q1vkvQqyR5d/HdJnu2u7rM3Srm6crLIkq8Abon5b9uR78cS2myI/z+Phmm+DeuP5Y2eApRQ5ZCgiq5ruVHixajAbv3XcLP9TOzMY04R6HtVPUobhVsncA7IV6QMm5c38L0+sKDncefW23zu7ZybKa7QhYuF2govqQKtHPWT6Y=,iv:A0oT5pIvjysQzoQlwkoIPi9xX6bSol1Ard651eYltt8=,tag:XRokz6rmGoWwm+KkUjZNlQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
