---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app technitium-dns
spec:
  chartRef:
    kind: OCIRepository
    name: technitium-dns
  interval: 1h
  values:
    fullnameOverride: external-dns-technitium
    provider:
      name: rfc2136
    env:
      - name: EXTERNAL_DNS_RFC2136_HOST
        value: "172.16.0.200
      - name: EXTERNAL_DNS_RFC2136_PORT
        value: "53"
      - name: EXTERNAL_DNS_RFC2136_ZONE
        value: "${SECRET_DOMAIN}"
      - name: EXTERNAL_DNS_RFC2136_TSIG_KEYNAME
        value: "external-dns"
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG
        value: "hmac-sha512"
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: &secret technitium-dns-secret
            key: EXTERNAL_DNS_RFC2136_TSIG_SECRET
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - gateway-httproute
      - service
    txtOwnerId: technitium
    txtPrefix: "k8s."
    domainFilters:
      - ${SECRET_DOMAIN}
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret