apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:2Oji0AKhegk8Z9Qr/pTEYwuahSvd8tzf83ycIMeEr/sMSAT/ASFyzAJJA0EZ1PWPjmUuvGzJ5DfGWJCRVfwKgjoZe8qSSxymULAgiyUNymx9HNB3vU0M0AGmUYRKruLlqEmFrU92fxu8Jxo9w14JvuTtOowE2p1WmoqMCZU2ldU9rGMz+21HJmUlALy42HC6sbuc8t1UUSYazD6VBumUDAfgMqvAV0N28dlb3aI59O+emayq,iv:rD16KaGcUFZNfbPQg9uEFwU0S9JQtl0+QZpq2Vscf1k=,tag:VaCjwuygIPva0fmruZ1g5Q==,type:str]
sops:
  age:
    - recipient: age1qeu5ft3kqvvwz2pkdmmxw7vsrr6gydegmm7km25rqvqexkhga9gq228h6z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRG9vckZWWW1od1JkaVJB
        ZzB0TWlTaEoybWl2ZnNSUkxDUjR2a3hXYzNJCnBNRXFKRTBaVUdabHdiOFVuVU0r
        aXYrOHBPMWFuVjJ4NGp1R2NxTEpMaE0KLS0tIFIwZGRIRTY5dm5SblFZTGF6bHJD
        TVQ4S1dNcXBRQVpoa3Z4MFlNY1gySGMK7L+RH4FdW3uZeBS7EOlVC3vOd505hzeZ
        FjKdt5GKXiIDfgAechU/B0FUuv40YkZl6wNIeK3fcnoq/2E3ry3nLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T17:02:23Z"
  mac: ENC[AES256_GCM,data:RHdOdbuHUvhnY6B7eIiAzp6xHKCQq5uGHeB2q4hcbC+4aCEW+QmKPAz0ffY7Bn8GuGZCyjhcorwuixj+hd1NSw6403i+/eKS1X5HtFC3PD/OlZvEN7+W5c4z/QKnfJge6ckNf6hiXgPg54iTMF5a5TKFnV+wpTnUpFie07YqdQA=,iv:hjVPBnitS7KtmvJ9hZRTW9Cy8qYa0mwJofKU2iI6O6Y=,tag:bjsPA0BSacDg/FqRwNu8pw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
