apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:rYvNe1yS7QSwfAx4C1Te44xA/fLFEJDQlAHnjexjnHZeJDI0XEdt3F5IhnbvB7c2ljHWv9ahrMQenkigQK6sSNq9YxBYJO326l6y3Mv+zpHLwYKkbwJuVTxSharAhyVGEHFN5jXuLgjo3zWoSxfwNmlfjIml71UTyI/3jWpg338/tlY9EaKUWVgvPp1LwSLimmJfN+R4HVrrO/RM3toEW1WUdNaF/PNIxmB14NxSbwWoePNr,iv:iWjD4+PKQNIAi4Pfr3Sd0bh0GWCpidzrVfyhOpoxSTs=,tag:79KI2izcNgIcmYQqQHGQmg==,type:str]
sops:
  age:
    - recipient: age1qeu5ft3kqvvwz2pkdmmxw7vsrr6gydegmm7km25rqvqexkhga9gq228h6z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraEg2T0ZSTVZIREdleEF4
        U2s2dWMxUVY5QjAwSm9RUWd1RzBOSzVHVUdZClRsZ0dNL2pFT3A4QVJtY3gyTVhW
        eVQzSWVKZkZDa1Zsd2I0amRIOW12WUEKLS0tIHR0RFhzdHQwV21RRzlVakNYK3h2
        TjhoY0FERXJldVVKaHFVbEdCQ2hWWm8KYnWhlLwlAl9lJa7dpd8IxcCp/DpR1bV4
        nlMRCfiulUg5BQu/pgNflJOP20EkVsSUm2eO0LXanUwToyskQ0F3sA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T17:55:46Z"
  mac: ENC[AES256_GCM,data:pt+wWHjo1RcSVOuS91gqt3dJu56DXFZ8HPxwe1xlAbcdvwptu/LIdl4/4xzNhTPA6hpCuooD3ogHM7xLGOKvj9OIBj995bBWUMCwuXKugVTKMv5an1bPqi4/gshAQkXMxZqh6nsAMejbjW7OyfMPxFD+XYGHtl41m4Lz8FFNCK0=,iv:7QJGnFThRd0x8l6BfuJw9NfSncusKzowkfyINcRsx70=,tag:aFpCLX2ITXtEXy/hKDjsSg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
