apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:l1V0Q0ppaxQxEtdqpip9dkWB/n/xR9V5i+8h4oqVFon4ClgnNA57fQ==,iv:jYg5vFcwq+eyRNFHyb0eXlv2wV8jrtrOjJFuVvkpu+c=,tag://l/J5y/FUPUNV4sBNGcGA==,type:str]
sops:
  age:
    - recipient: age1qeu5ft3kqvvwz2pkdmmxw7vsrr6gydegmm7km25rqvqexkhga9gq228h6z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdmtoOS9NZ3UrT2tVTHM0
        WGZZd25wVUlMTVJQVTdGK0J3Sm9TYytxWjM4CjJDMnN3OTg0WmtvNXQ3Q0NGTkIx
        VTB6dTZNaUdGUDhTY3M5WUZJNDB5QXcKLS0tIGpDcEFrOE5reDNRL09xbENZdFRj
        Y25mUWpDTkZjN3d5TmZFNG13K0NTekEKREvNMd8Q1MaBc6eAcz2MNI4+hIsIJ0GS
        NxI1EyARStg3Kqe338K212BOTau0ig3jC6yxXXFwAwXwEpKpyNSBSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T17:55:46Z"
  mac: ENC[AES256_GCM,data:eP0a4y6krGV1JobiUFtRPauf0GNTiOvwrka6w+YfsLwHYURb8fnmG5kxYuL2ppAUgmwUhlthfXPUUKt254akYg4Aa9cyhW7F3LEY/BWgMahdyA3y9qP8+7xb4NnPzQ/VgaQU73AdJ2Cc7VBe8Tri/zyNHC0ceISTIWgh+aSSqOE=,iv:ZmTCOgRjTLQUl7vNhmvCB1IPevqeowj36DhuU0zpaac=,tag:xBy0BPS0ejazO2+IVtcQeQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
