---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teslamate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: teslamate-secret
    template:
      data:
        # Teslamate
        ENCRYPTION_KEY: "{{ .TESLAMATE_ENCRYPTION_KEY }}"
        DATABASE_NAME: teslamate
        DATABASE_HOST: postgres-rw.database.svc.cluster.local
        DATABASE_PASS: "{{ .TESLAMATE_POSTGRES_PASS }}"
        DATABASE_USER: "{{ .TESLAMATE_POSTGRES_USER }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: teslamate
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_PASS: "{{ .TESLAMATE_POSTGRES_PASS }}"
        INIT_POSTGRES_USER: "{{ .TESLAMATE_POSTGRES_USER }}"
  dataFrom:
    - extract:
        key: teslamate
    - extract:
        key: cloudnative-pg