
name: Test
on:
  workflow_dispatch:

jobs:
  Organize:
    runs-on: home-ops-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          enable-cache: false

      - name: Execute echo
        run: echo "This is working !"