
name: Test
on:
  workflow_dispatch:

jobs:
  Organize:
    runs-on: home-ops-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install uv
        uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7.2.1
        with:
          enable-cache: false

      - name: Execute echo
        run: echo "This is working !"